global:
  scrape_interval: 15s 
  evaluation_interval: 15s

scrape_configs:
  # n8n
  - job_name: 'nexus_n8n'
    static_configs:
      - targets: ['nexus_n8n:${N8N_PORT}']
    metrics_path: '/metrics'
  
  # Node Exporter
  - job_name: node_exporter
    static_configs:
      - targets: ['nexus_node_exporter:${NODE_EXPORTER_PORT}']

  # Jenkins 
  - job_name: 'nexus_jenkins'
    static_configs:
      - targets: ['nexus_jenkins:${JENKINS_PORT}']
    metrics_path: '/prometheus'
  
  # PostgreSQL Exporter
  - job_name: postgres_exporter
    static_configs:
      - targets: ['nexus_postgres_exporter:${POSTGRES_EXPORTER_PORT}']

  # Traefik 
  - job_name: 'nexus_traefik'
    static_configs:
      - targets: ['nexus_traefik:${TRAEFIK_METRICS_PORT}']
    metrics_path: '/metrics'

  # Cadvisor
  - job_name: cadvisor
    static_configs:
      - targets: ['nexus_cadvisor:${CADVISOR_PORT}']
