# jenkins docker-compose.yml
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: nexus_jenkins
    profiles: [ 'cicd' ]
    hostname: jenkins.${BASE_DOMAIN}
    env_file:
      - ../.env
    environment:
      - TZ=Asia/Seoul
    ports:
      - "${JENKINS_PORT}:8080"
      - "${JENKINS_SLAVE_PORT}:50000"
    volumes:
      - ./data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

    restart: unless-stopped

    # Traefik 라벨
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jenkins.rule=Host(`jenkins.${BASE_DOMAIN}`)"
      - "traefik.http.routers.jenkins.entrypoints=websecure"
      - "traefik.http.routers.jenkins.service=jenkins"
      - "traefik.http.routers.jenkins.tls.certresolver=letsencrypt"
      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik_network"

      # 헤더 설정
      - "traefik.http.middlewares.jenkins-headers.headers.customrequestheaders.X-Forwarded-Proto=https"

    networks:
      - nexus_network

networks:
  nexus_network:
    external: true