# postgres docker-compose.yml
services:
  postgres:
    image: postgres:17.4
    container_name: nexus_postgres_db
    profiles: [ 'backbone' ]
    env_file:
      - ../../.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: ${POSTGRES_INITDB_ARGS}
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: unless-stopped
    networks:
      - nexus_network  
      
networks:
  nexus_network:
    external: true